# Generated by Django 5.0.3 on 2024-06-15 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('berita', '0002_artikel_create_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artikel',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
